### ISSUE TITLE
conda environment suitable to get code running.

### ISSUE THREAD

**Issue by johndpope** [ciaua/unagan#10]
I'm running on python 3.8.5
and the generate fails.....

sr: 22050
hop_length: 256
duration: 10
Traceback (most recent call last):
  File "generate.py", line 402, in <module>
    main(args)
  File "generate.py", line 268, in main
    num_frames = int(np.ceil(duration * test))
TypeError: can't multiply sequence by non-int of type 'float'

in a previous git issue - it mentions specific numba / librosa versions needed too.

I'll do some testing with 3.7 and save config.

**Comment by johndpope** [comment]
I'm testing on your code with 3.8

```
conda create -n newenv python=3.8
conda activate newenv
pip install -r requirements.txt
```


**librosa==0.8.1**

**numba==0.54.1**


will attempt to downgrade these. 

UPDATE
not sure why - but am hitting this error. 
py38) ➜  unagan git:(master) ✗ python generate.py -d singing -a hc --duration 10 -ns 5

sr: 22050
hop_length: 256
duration: 10
test: 86.1328125
Traceback (most recent call last):
  File "generate.py", line 404, in <module>
    main(args)
  File "generate.py", line 270, in main
    num_frames = int(np.ceil(duration * test))
TypeError: can't multiply sequence by non-int of type 'float'

python --version
Python 3.8.5
```python

    print("sr:",sr)
    print("hop_length:",hop_length)
    print("duration:",duration)
    
    test =  (sr / hop_length)
    print("test:",test)

    num_frames = int(np.ceil(duration * test))
```



If I coerce the line to int
   test =  int(sr / hop_length)

I get
TypeError: ufunc 'ceil' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

**Comment by johndpope** [comment]
python generate.py -d singing -a hc --duration 10 -ns 5

not sure why - but on my box - some of these parameters passed are problematic.
If I run 
**python generate.py -d singing**  
it generates samples without error.
