### ISSUE TITLE
Error running training against folder of wave files / missing vocals.npy

### ISSUE THREAD

**Issue by johndpope** [ciaua/unagan#11]
I go through all the steps....but hit an error

```shell

python scripts/train.*.py
20211112_070808
/home/jp/Documents/gitWorkspace/unagan/scripts/train.hierarchical.py
tr: 107, va: 200
20211112_070808
Training...
Traceback (most recent call last):
  File "scripts/train.hierarchical.py", line 622, in <module>
    batch = next(inf_iterator_tr)
  File "scripts/train.hierarchical.py", line 159, in make_inf_iterator
    for data in data_iterator:
  File "/home/jp/miniconda3/envs/torch/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/jp/miniconda3/envs/torch/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/jp/miniconda3/envs/torch/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/jp/miniconda3/envs/torch/lib/python3.8/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/jp/miniconda3/envs/torch/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/jp/miniconda3/envs/torch/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jp/miniconda3/envs/torch/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "scripts/train.hierarchical.py", line 38, in __getitem__
    voc = np.load(voc_fp)
  File "/home/jp/miniconda3/envs/torch/lib/python3.8/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: "./training_data/exp_data/mel/04 Baby, Baby Don't Cry Instrumental mono Smokey Robinson.40_50/vocals.npy"


```

looking at my files

I can clearly see /training_data/exp_data/mel/04 Baby, Baby Don't Cry Instrumental mono Smokey Robinson.40_50.npy

but code is expecting a folder with associated vocals.npy
"./training_data/exp_data/mel/04 Baby, Baby Don't Cry Instrumental mono Smokey Robinson.40_50/vocals.npy"

I'll keep digging around at training code. I get the first step is to make sure it's training on singing only. Is there a specific reason for this? could this code not just accept drums only training data. 

```python

class VocDataset(Dataset):
    def __init__(self, ids, path):
        self.metadata = ids
        self.path = path

    def __getitem__(self, index):
        id = self.metadata[index]
        voc_fp = os.path.join(self.path, id, 'vocals.npy') // shouldn't file be automagically generated? 

        voc = np.load(voc_fp)

        return voc

    def __len__(self):
        return len(self.metadata)

```

UPDATE
reading here -   we need to update the code so that there's a new file created in a nested directory. I'll take a look if there's a quick fix.
https://github.com/ciaua/unagan/issues/3#issuecomment-774820967

**Comment by johndpope** [comment]
see PR
